{% set name = "maplibre" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maplibre-{{ version }}.tar.gz
  sha256: 9c80e818e96f37dee0bfcdc0bced0307758ca6090dbe7748e1133d07edfe0095

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - jinja2 >=3.1.3
    - pydantic >=2.5.3
    - anywidget >=0.9.0
    - branca
    - eval-type-backport
  run_constrained:
    - pandas >=2.1.4
    - geopandas >=0.14.2

test:
  imports:
    - maplibre
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eodaGmbH/py-maplibregl
  summary: Python bindings for MapLibre GL JS
  license: MIT
  license_file: LICENSE.md
  doc_url: https://eodagmbh.github.io/py-maplibregl

extra:
  recipe-maintainers:
    - crazycapivara
    - giswqs
