{% set name = "maplibre" %}
{% set version = "0.3.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maplibre-{{ version }}.tar.gz
  sha256: 3c1b6bfa740a035f32682e7ef9a54172a019770a3e1317eea6f3e66b8cf0b1a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    # - shiny >=0.7.0
    # - htmltools >=0.5.1
    - jinja2 >=3.1.3
    - pydantic >=2.5.3
    - anywidget >=0.9.0
    - branca
    # - questionary
  run_constrained:
    - pandas >=2.1.4
    - geopandas >=0.14.2

test:
  imports:
    - maplibre
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eodaGmbH/py-maplibregl
  summary: Python bindings for MapLibre GL JS
  license: MIT
  license_file: LICENSE.md
  doc_url: https://eodagmbh.github.io/py-maplibregl

extra:
  recipe-maintainers:
    - crazycapivara
    - giswqs
