{% set name = "maplibre" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/maplibre-{{ version }}.tar.gz
  sha256: 4b2f0a28c8b29db75ad945e5c60944f7a749a1d8b6e340f88fbec36ca52b7bf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - shiny >=0.7.0
    - htmltools >=0.5.1
    - jinja2 >=3.1.3
    - pydantic >=2.5.3
    - anywidget >=0.9.0
    - questionary
  run_constrained:
    - pandas >=2.1.4,<3.0.0
    - geopandas >=0.14.2,<0.15.0

test:
  imports:
    - maplibre
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eodaGmbH/py-maplibregl
  summary: Python bindings for MapLibre GL JS
  license: MIT
  license_file: LICENSE.md
  doc_url: https://eodagmbh.github.io/py-maplibregl

extra:
  recipe-maintainers:
    - crazycapivara
    - giswqs
