{% set name = "maplibre" %}
{% set version = "0.2.7" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maplibre-{{ version }}.tar.gz
  sha256: 8c6f58cda97ea74ebedc0de24f7aadc69deae4b510028bc0089b6a079084fa23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - shiny >=0.7.0
    - htmltools >=0.5.1
    - jinja2 >=3.1.3
    - pydantic >=2.5.3
    - anywidget >=0.9.0
    - branca
    - questionary
  run_constrained:
    - pandas >=2.1.4,<3.0.0
    - geopandas >=0.14.2,<0.15.0

test:
  imports:
    - maplibre
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eodaGmbH/py-maplibregl
  summary: Python bindings for MapLibre GL JS
  license: MIT
  license_file: LICENSE.md
  doc_url: https://eodagmbh.github.io/py-maplibregl

extra:
  recipe-maintainers:
    - crazycapivara
    - giswqs
